#Store all your config's here.
#added to gitignore so will not be syned

#Backup in ~/Desktop/config.py_backup

shodan_api="70HHxcFxIdbSmFpGVau9Ph4ya3zJmxES"
bing_api=""
github_access_token=""
builtwith_api=""
censysio_id="3c16ffe2-5261-446f-8e2d-ba68c44cf4b5"
censysio_secret="6xR0rNDJAkBY0NZ7aAdqjK0Ocy6Z35Oo"
facebook_access_token = ""
flickr_api=""
google_api=""
google_cse_key=""
google_cse_cx = ""
hashes_api=""
ipinfodb_api=""
jigsaw_api=""
jigsaw_password=""
jigsaw_username=""
linkedin_api=""
linkedin_secret=""
pwnedlist_api=""
pwnedlist_iv=""
pwnedlist_secret=""
reddit_id = ""
reddit_secret = ""
spyonweb_access_token = ""
twitter_consumer_key=""
twitter_consumer_secret=""
twitter_access_token = ""
twitter_access_token_secret = ""
zoomeyeuser = ""
zoomeyepass = ""
clearbit_apikey = ""
emailhunter="28054d2a2a1c0be8fd06c6e13d3b90a37541589b"
jsonwhois=""
instagram_token = ""
instagram_client_id = ""
instagram_client_secret = ""
fullcontact_api = ""
mailboxlayer_api = ""
virustotal_public_api =""
